# Generated by Django 6.0.4 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
